# Generated by Django 5.0.1 on 2026-02-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('passport_id', models.CharField(max_length=100, unique=True, verbose_name='Passport ID')),
                ('department', models.CharField(max_length=200, verbose_name='Department')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='interns/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Intern',
                'verbose_name_plural': 'Interns',
                'ordering': ['-created_at'],
            },
        ),
    ]
