# Generated by Django 5.0.1 on 2026-02-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='passport_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Passport ID'),
        ),
    ]
