# Generated by Django 5.0.1 on 2026-02-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_alter_intern_passport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
    ]
